### ISSUE TITLE
error with vMixScriptList.json does not exist

### ISSUE THREAD

**Issue by rayboomservice** [SysProfile/vMixIDE#1]
I'm not a programmer. I downloaded the indicated files and compiled them with VISUAL STUDIO 2022, but it always gives me an error due to the lack of the file in question. I don't know where I'm going wrong. I ask for your help.

**Comment by SysProfile** [comment]
Sorry for the delay, I'm working hard these days. It is programmed in the code that if the file does not exist, you should download it. I add the file to the project, Github doesn't include it automatically. Tell me if it works for you.
